[package]
name = "ipcv"
version = "0.1.0"
edition = "2024"

# [[bin]]
# name = "server"
# path = "src/server.rs"

# [[bin]]
# name = "client"
# path = "src/client.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
colored = "3.1.1"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.34"
hostname = "0.4.2"
humantime = "2.4.0"
image = "0.25.10"
itertools = "0.15.0"
local-ip-address = "0.6.13"
nokhwa = { version = "0.10.11", features = ["input-native", "output-threaded"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"

[target.'cfg(unix)'.dependencies]
termios = "0.3.3"
